spring:
  application:
    name: notification-service
#    version: @project.version@
  profiles:
    active: home
  webflux:
    base-path: "/home/notification"
  rabbitmq:
    host: rabbitmq-headless
    port: 5672
    username: notification
    password: ${rabbitmq-password:dummy}
    virtual-host: /notification
    connection-timeout: 10s
    requested-heartbeat: 10s

server:
  port: 6200

logbook:
  format:
    style: json

logging:
  level:
    org.zalando.logbook: trace

rabbit:
  alert:
    queue: notification.prod.alert

discord:
  bot:
    skippy:
      token: ${discord_bot_skippy_token:dummy}

---

spring:
  config:
    activate:
      on-profile: local
  rabbitmq:
    host: localhost

server:
  port: 6003
management:
  server:
    port: 8003

logbook:
  format:
    style: http

rabbit:
  alert:
    queue: notification.dev.alert

---

spring:
  config:
    activate:
      on-profile: test
  autoconfigure:
    exclude: org.springframework.boot.amqp.autoconfigure.RabbitAutoConfiguration